language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
  - pip install codacy-coverage
script:
  - python setup.py test
after_success:
  - coverage xml
  - python-codacy-coverage -r coverage.xml
