#!/usr/bin/env python

from plotxhmm.plotxhmm import Parser, Interval

parser = Parser('tests/normalized_zscores.txt')

interval = Interval('22', 18000000, 18500000)
subset = parser._zscores_subset(interval)
parser.plot_interval(interval, 'HG00113', 'debug/test.pdf')
