#!/usr/bin/env python3.6

from plotxhmm.plotxhmm import Parser, Interval

print('Hello, World!')

parser = Parser('tests/test_normalized_zscores.txt')

print(parser._df.shape)
print(parser._df.index)

interval = Interval('22', 1000, 2000)

print(interval.chromosome)
